### ISSUE TITLE
[Enhancement]: Add manual documentation for VestingTerms 

### ISSUE THREAD

**Issue by pjohnmeyer** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#204]
### Description of Enhancement :

Add "prose" documentation, including graphs, to better explain how VestingTerms and related vesting types work.

### Why is this Needed?

VestingTerms and its related objects could use more explanation than can be easily generated for documentation generated via JSON-Schema. Describing some sample cases with detailed prose and visual aids will help folks generate their VestingTerms correctly.

**Comment by pjohnmeyer** [comment]
Also this. https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/discussions/257#discussioncomment-3182420

**Comment by JSv4** [comment]
@pjohnmeyer, heads-up that, with the new documentation revamp, you're going to want to add your content for this in the `/docs/explainers` section. We can then add an entry in `/docs/explainers/.pages` to create a nav link in the sidebar for the "Architecture" page [here](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/explainers/Architecture/).

**Comment by pjohnmeyer** [comment]
@JSv4 got it. I was using the supplemental doc support (#232) so it would show up inline with the schema docs. Perhaps a combination of the two would be best.

**Comment by pjohnmeyer** [comment]
@JSv4 I've added everything using supplemental doc support. If you want to pair with me on moving things around I'm open to it but this meets the need.

**Comment by JSv4** [comment]
That works for me @pjohnmeyer. We can continue to improve / expand the docs. I'll need to take a look at this. Hey, I know we were going to meet up for the release tomorrow. I had to move my flight from Friday to Thursday. Are you able to meetup for an hour or so on Friday to merge the final commits and release v1.0.0? I'll shoot you an e-mail too.
