### ISSUE TITLE
[Enhancement]: Review and update contributors guidelines

### ISSUE THREAD

**Issue by pjohnmeyer** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#211]
### Description of Enhancement :

Specifically, in #201 we discussed writing down the "rule" that enums not be defined inline.

More generically, we should review the guidelines to see if they are up-to-date before we go public.

**Comment by JSv4** [comment]
Things to balance here:

- Quality 
- Brevity

General thought here is it doesn't need to be too heavy. Let's just take a first stab at something to put in contributing.md.

**Comment by JSv4** [comment]
Hey @strichter, have you had a chance to pull together any material you'd like to incorporate into our contributors' guidelines?
