### ISSUE TITLE
[Enhancement]: Make Schemas Available at "opencaptablecoalition.com"

### ISSUE THREAD

**Issue by wuz** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#248]
### Current Behavior:

Running the schemas through a JSON validator like Ajv, the schemas listed here are a bit broken. Many of the schemas reference `opencaptablecoalition.com` but they aren't actually present on that site. For instance, the `Address` references the `CountrySubdivisionCode` schema like this: 
```
      "$ref": "https://opencaptablecoalition.com/schema/types/CountrySubdivisionCode.schema.json"
```
but that URL is currently broken. This causes validators with external reference checking to fail.

### Expected Behavior:

`$ref` and `$id` fields in the schemas point to valid files.

### Steps to Reproduce:

Run a validator with external reference checking (like [Ajv](https://www.npmjs.com/package/ajv)) against a schema file with a reference.

**Comment by JSv4** [comment]
Hey @wuz, we should put them on opencaptablecoalition.com. That said, you can download the repo and load the schemas directly using AJV. Look at our validation code to see how to use AJV to load the schemas from a dir:

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/72af3067097d5adf58cccba20c0d60d894f82552/utils/validate.mjs#L105-L171

Agreed it would be a nice enhancement to 1) at least document how schemas should be loaded **now** and 2) make them available at the actual opencaptablecoalition.com domain.

What do you think @pjohnmeyer or @jacobyavis?

**Comment by wuz** [comment]
Gotcha, makes sense! I did download the schemas, but just passing them straight into Ajv doesn't seem to work (for the reason in the issue). Makes sense to load them all in first though!

Thanks for the note!

**Comment by JSv4** [comment]
Sure @wuz, no problem. I'm going to switch this from a bug to an enhancement request. Think it's a good idea to make the schemas available at our urls, as you suggested.

**Comment by JSv4** [comment]
Hey @xudiera, anything I can help with here? Would be great to get this running!

**Comment by xudiera** [comment]
@JSv4 will it make sense to use as a URL for each file the URL of the raw JSON schema on the repository? In that way you get the right JSON schema for all branches and tags, e.g.,

https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/enums/AccrualPeriodType.schema.json

https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/v1.0.0-b2/schema/enums/AccrualPeriodType.schema.json

**Comment by pjohnmeyer** [comment]
@xudiera I think your suggestion here is the minimally viable solution.

**Comment by JSv4** [comment]
Bringing this comment thread up-to-date. Per our most recent TWG discussions, GitHub is not a workable host due to the 5,000 page view limit. Given the # of schemas required for a single validation, that will probably be used up quickly, probably just be dev and GitHub action requests.

@xudiera is working on some tooling to update our $refs as needed (for versioning the schemas, changing the host, etc). @JSv4 and @pjohnmeyer are working with our web admin to work out a deployment strategy to the opencaptablecoalition.com domain.

**Comment by pjohnmeyer** [comment]
We attempted to wrap this up prior to the 1.0.0 release but were concerned about generating something incorrect. We will resolve in a near-term follow up.

Releases will be made available at `https://schema.opencaptablecoalition.com/v/M.m.p` e.g.: `https://schema.opencaptablecoalition.com/v/1.0.1`
