### ISSUE TITLE
[Enhancement] - MFN field for convertible notes

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#250]
As raised by @magonjr, some systems are tracking MFN flags for Convertibles and Notes, whereas the beta only tracks SAFEs. Add a flag to NoteConversionMechanism similar to what's in SAFEConversionMechanism.  

### Discussed in https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **magonjr** June 27, 2022</sup>
We propose adding a MFN field for convertible notes. We noticed that OCF only has a Most Favored Nations Date field for SAFEs, but not for convertible notes. While it’s a pretty rare mechanic for convertible notes, it is possible for convertible notes to have MFN clauses.</div>

**Comment by JSv4** [comment]
@JSv4 to assign to Naveed.

**Comment by naveedn** [comment]
PR Created: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/290
