### ISSUE TITLE
[Question]: Does Open Cap Table support Profit Interest Units? 

### ISSUE THREAD

**Issue by shulmanbrent-pave** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#272]
### Question: Does Open Cap Table support Profit Interest Units? 

Profit Interest Units are often used for by LLCs and an equity vehicle. Does OpenCapTable support PIUs? and if, how? 

### Anything else we need to know?

No

**Comment by pjohnmeyer** [comment]
@shulmanbrent-pave at this point it does not. I remember having discussions about this early on and it being deemed out of scope for 1.0, but I could be mistaken. @JSv4 might have notes.

Is this an enhancement you or somebody at your organization would be willing to work on?

**Comment by JSv4** [comment]
@shulmanbrent-pave, the Steering Committee and Technical Working Group decided to scope the initial release to DE C-Corporations. We expect a lot of the same schemas can be re-used for LLCs, however. We'd definitely welcome a proposal on what an LLC-flavored OCF might look like. If there's any interest from Pave in working on that, let's chat offline.
