### ISSUE TITLE
Rename "Base" schemas to better reflect composition, not inheritance

### ISSUE THREAD

**Issue by pjohnmeyer** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#273]
### Discussed in https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/discussions/266

There are a few proposed solutions in the original discussion, but no chosen solution yet.

**Comment by JSv4** [comment]
Per the discussion:

"A StockAcceptance is allOf these things: an Object, a Transaction, a SecurityTransaction, and an Acceptance. It also meets the following criteria... ".

Let's remove the prefixes or suffixes on the primitives.
