### ISSUE TITLE
[Question]: Any notable opens source *tools* which implement / use the formats?

### ISSUE THREAD

**Issue by srabi** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#274]
Just found you people while struggling with my CAP table ...
I wonder if you know of and can recommend and open source tools which implement the formats into something I can use for my own cap table management?

**Comment by pjohnmeyer** [comment]
@srabi not to my knowledge. The [Open Cap Table Coalition](https://www.opencaptablecoalition.com/) certainly intends for an ecosystem of tools will be built up around this standard, and is making efforts to that end.

**Comment by JSv4** [comment]
As @pjohnmeyer said, @srabi, nothing publicly released that we know of, but the goal here is to empower the industry to build bespoke solutions on top of a consistent data format. The Coalition plans to develop some tooling for public release, and I know a number of Coalition members have built or are building OCF-compatible software, though what I am aware of would probably would be closed source.
