### ISSUE TITLE
[Enhancement]: Provide alternative to ISO 3166-2 for Jurisdiction Fields

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#315]
### Description of Enhancement :

Replace the concept of using ISO 3166-2 for the Country Subdivision Code type with an enumerated list that matches valid jurisdictions for countries outside of the United States.

### Why is this Needed?

Currently, it looks like the Country Subdivision Code is a string field that is meant to be validated against the ISO 3166-2 code. 

The ISO 3166-2 list doesn’t really work outside the U.S. because the code does not match the jurisdictions of many other countries. For example, the subdivision of the United Arab Emirates are the seven Emirates but that does not match the jurisdictions list for the country which has some 52 jurisdictions including Abu Dhabi Global Market which is used by many regional startups. The same issue existing with the United Kingdom where the most common jurisdiction is actually “England & Wales”. 

### Anything else we need to know?

I have not been able to find a good source for a master list of global legal jurisdictions for company formations, but it must exist somewhere.

**Comment by JSv4** [comment]
Thanks for raising @arthur-clara. 

It seems like there are two distinct but related issues here:

1. Subdivisions for the purpose of tracking legal jurisdictions
    1. Here we could create an enumeration of jurisdictions. We don't really want to maintain this, but if we create a custom enum, we're open to people helping maintain the list.
2. Subdivisions for the purpose of mailing addresses (where such subdivisions are needed)
   1. Here we could see what some of the commonly-available commercial address validation tools use as inputs and, to the extent the schemas don't align with their required inputs, we could tweak our address schema to better align with those. Do you have any services like this you like?
