### ISSUE TITLE
[Enhancement]: Add "numbered shares" field to stock issuance object

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#316]
### Question:

Does the OCTF have a standard for dealing with numbered shares?

### Anything else we need to know?

In several jurisdictions including Abu Dhabi Global Market which is used for many MENA-based startup holding companies, the authorizing body requires tracking of numbered shares. In other words, shares are non-fungible. (e.g. If Shareholder A transfers 50,000 shares, they don't just transfer a block of 50,000 shares, they transfer shares numbered from 1,000,001 to 1,050,000)

One potential option that has been explored is using the custom-id field for tracking these numbers but that field is still valuable for share certificate tracking in various jurisdictions.

**Comment by JSv4** [comment]
@arthur-clara, thanks for raising this one. We're definitely open to adding a new field here. We're discussing this now, but none of us are particularly familiar with the requirements of these types of jurisdictions. What do you think an additional field would look like here? Also, is it common for these shares to be re-combined into a single certificate later, or is this pretty much a one way street where you see the blocks get smaller and smaller over time?

**Comment by mmurto** [comment]
We also use share numbers in Finland, so I'll try and chime in here.

Companies are not required, and often do not issue share certificates for shares at the same time the share issue is done. Companies are required to keep a shareholder register on the shares and their holders indicating the details of each shareholders and the number of specified shares or share certificates broken down by share class and the date of issue of the shares.

At the request of the shareholder, the company shall issue share certificates for the shareholder's shares. The company must also at the request of the shareholder split and combine share certificates. For many companies, their shareholders' agreement includes provisions with which the shareholders agree not to request share certificates, so many companies may not issue any certificates at all.

In practice this leads to us referring to share numbers in many places where OCF uses `security_id`. For example, the sample stock issuance transaction:

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/3ab31dbdced4eca13a5bae5a30dcded7c6cc1873/samples/Transactions.ocf.json#L583-L602

Here it would probably make sense to be able to indicate which share numbers were issued, for example share numbers 1-1000. It would also make sense to be allowed to omit the `security_id` field, as there often are no share certificates with an id at this point. The main identifiers would be the share numbers and `stock_class_id`.

The same applies to other transactions, such as stock transfer. Shareholders can transfer share by reference to the share numbers, no share certificate (or `security_id`) has to exist.

I'm not sure what would be the best way to accommodate this, but I hope this helps your discussion. Happy to talk more if needed!

**Comment by JSv4** [comment]
@arthur-clara, @mmurto, what if we added a separate share number tracking field that has a list of objects tracking the min and max number of shares (inclusive) that are part of the issuance? 

So something like this:

```json
[
    {
        "min": 1, 
        "max": 100
    },
    {
        "min": 5012,
        "max": 5012
    }
]
```

This would let us handle situations where (for whatever reason) you have non-continuous ranges.
