### ISSUE TITLE
[Enhancement]: Capture some sort of capitilization definition in the convertible issuance transaction.

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#317]
### Description of Enhancement :

Capture some sort of capitalization definition in the convertible issuance transaction. It is currently only captured in the convertible conversion transaction using security and class id of existing securities at the time of transaction.

### Why is this Needed?

At the time of convertible issuance, there is usually some definition of capitalization definition strategy (e.g. pre-money vs post-money). From my review, it looks like that there is nowhere to store this definition in the issuance event. Therefore, if a cap table was ported from one provider to another using OCTF that contains convertibles that have NOT yet converted and have an associated convertible conversion transaction, it appears like that data would be lost from the data set. 

### Anything else we need to know?

I believe a challenge that is going to have to be overcome is that the actual capitalization definition in the transaction event is id based which makes sense at time of transaction but that strategy may not work for issuance transactions as it may include existing and future securities and classes.

**Comment by JSv4** [comment]
@arthur-clara, the reason we only defined this at the time of conversion was we couldn't come up with a satisfactory way to define capitalization at the time of issuance in a structured way. What we ultimately arrived at was storing the natural language definition at the time of issuance for certain `ConversionMechanisms` and then having the `capitalization_definition` field in the ConvertibleConversion object to "show your work" basically at the time of conversion:

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/384e5de660f92b8de5eea1712a071e983b04ea20/schema/objects/transactions/conversion/ConvertibleConversion.schema.json#L21-L44

Essentially, this lets you show what went into the total capitalization calculation and resulting conversion amount at the time when it's easily reduced to structured data. It's much more challenging to do this upfront at issuance (probably not impossible, but it would be quite complex to handle all corner cases). 

This works hand-in-glove with some of the fields in our `ConversionMechanism` definitions. For example, the `PercentCapitalizationConversionMechanism` provides a free text field to include the natural language definition of capitalization if you want to / can include that:

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/384e5de660f92b8de5eea1712a071e983b04ea20/schema/types/conversion_mechanisms/PercentCapitalizationConversionMechanism.schema.json#L1-L28

This _is_ defined at the time of issuance.

Then, when you actually do the conversion event itself, you'd use the `CapitalizationDefinition` type and field on the conversion transaction to track what objects (stock plans, stock, convertibles, whatever) actually went into the capitalization calculation. 

Based on all this, I **think** we're providing what you need? If you want to store capitalization information at the time of issuance in a structured format, definitely open to it if you can come up with something. Definitely feel free to propose something!
