### ISSUE TITLE
The samples/Manifest.ocf.json file names don't match the actual filenames in samples

### ISSUE THREAD

**Issue by regebro** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#328]
### Discussed in https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/discussions/327

Currently in `samples/` all the files end in `.ocf.json`, but inside of `Manifest.ocf.json` the files are just referred to with the `.json` ending.

Which one is the correct ending? I have a branch using `.ocf.json` consistently, I can make a merge request if that's the correct ending.

**Comment by JSv4** [comment]
Thanks for raising, @regebro! You're correct that it should be `.ocf.json`. I was working through a backlog of issues today, so I just went ahead and fixed this in a quick PR. Really appreciate your contribution though!
