### ISSUE TITLE
[Bug]: Investigate and Repair Possible Test Failure that Doesn't Trigger Failure in GitHub Action

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#355]
### Current Behavior:

As reported by @xudiera on today's TWG call, his branch had a test that failed for his PR that he needed to fix. The test and failure were both unrelated to changes he made, suggesting there is a test that's been failing in our test suite elsewhere. All of the GitHub actions passed, however, so we need to investigate to make sure that a) a test isn't silently failing and b), if it is, why our corresponding Action is not failing. 

### Expected Behavior:

If a test fails, GitHub Actions running it should fail too. 

### Steps to Reproduce:

@xudiera, can you add additional info here as needed?

**Comment by xudiera** [comment]
Running `npm run test` on the `main` branch results on:

![image](https://user-images.githubusercontent.com/3137781/211888983-b2cdc363-6619-4df1-8564-8e1e5959908c.png)

The majority of the test that are failing are trivially fix by updating the Copyright date from `Copyright © 2022` to `Copyright © 2023`

There is one of those failing test that needs to be fixed. On TableOfContents.test.ts the path on **View More** needs to be fix.

![image](https://user-images.githubusercontent.com/3137781/211890037-6c3934a3-1cf8-43a3-a774-09cb39b72ae6.png)

**Comment by xudiera** [comment]
Here is an example of the Action not failing when a unit test doesn't pass:
https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/actions/runs/3807911702/jobs/6478044986#step:5:43

I think this can be solve by  set the Fail-fast behavior on [jest.yml](https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/main/.github/workflows/jest.yml)

```
- name: Run Jest Tests
        run: npm run test
        shell: bash
```

See:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

https://github.com/github/docs/blob/2ec9640ca001ef7601c61891cf4538ab220e7961/content%2Factions%2Fusing-workflows%2Fworkflow-syntax-for-github-actions.md#example-running-a-script-using-bash
