### ISSUE TITLE
[Enhancement]: Replace conversion_timing property with a more robust capitalization definition object

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#357]
### Description of Enhancement :

Replace the conversion_timing property with a capitalization_definition object with the following properties:

|     Property    |     Type    |     Description    |     Required     | 
| --- | --- | --- | --- |
| Includes outstanding shares of capital stock | BOOLEAN | Set to true if the capitalization definition includes outstanding shares | REQUIRED |
| Outstanding options | BOOLEAN | Set to true if the capitalization definition includes outstanding options| REQUIRED |
| Promised options | BOOLEAN | Set to true if the capitalization definition includes promised options | REQUIRED |
| Unissued option pool | BOOLEAN | Set to true if the capitalization definition includes unissued option pools | REQUIRED |
| Option pool increase | BOOLEAN | Set to true if the capitalization definition includes any top-up of unissued pools as part of the Equity Financing | REQUIRED |
| Other Safes, convertible notes and other similar convertibles | BOOLEAN | Set to true if the capitalization definition includes other convertibles | REQUIRED |
| The convertible security itself  | BOOLEAN | Set to true if the capitalization definition includes the convertible itself | REQUIRED |

### Why is this Needed?

While the pre-money / post-money flag for conversion timing works for most convertibles, it does not work for all potential capitalization definitions for common convertibles.

This table, if included in the issuance objects also allows accurate cap table modelling functionality to be built on top of it. 

|                                                                        |     Techstars Fixed Percentage    |     YC Original Safe    |     YC Post-Money Safe    |     Standard Post-Money SAFE    |     Standard Pre-Money SAFE    |
|------------------------------------------------------------------------|:---------------------------------:|:-----------------------:|:-------------------------:|:-------------------------------:|:------------------------------:|
|     Outstanding shares of capital stock                              |              Included             |         Included        |          Included         |             Included            |             Included           |
|     Outstanding options                                              |              Included             |         Included        |          Included         |             Included            |             Included           |
|     Promised options                                                 |              Included             |         Included        |          Included         |             Included            |             Included           |
|     Unissued option pool                                             |              Included             |         Included        |          Included         |             Included            |             Included           |
|     Option pool increase                                             |              Included             |         Included        |    **Excluded**    |       **Excluded**      |       **Excluded**      |
|     Other Safes, convertible notes and other similar convertibles    |        **Excluded**        |   **Excluded**   |          Included         |             Included            |       **Excluded**     |
|     The convertible security itself                                  |              Included             |  **Excluded**   |          Included         |             Included            |       **Excluded**      |

### Anything else we need to know?

Structuring the capitalization definition in this manner leverages on the structures of OCTF as well as all types (except for the concept of promised options I think) are covered by the format.

Y-Combinator SAFE guide that uses this type of table (excluding the last row which has been added to deal with the Techstars Fixed Equity Convertible which includes itself but not other convertibles.)

https://www.ycombinator.com/assets/ycdc/Primer%20for%20post-money%20safe%20v1.1-2af8129e12effd9638eeab383b7309142c8f415e5cdb0bc210d573f779177a1c.pdf

**Comment by JSv4** [comment]
Love this @arthur-clara. Will need to take a closer look as well. Would you be interested in joining next week's Technical Working Group call to discuss? It's Noon to 1 PM Eastern on Tuesday. We can discuss the following week if that doesn't work?

**Comment by arthur-clara** [comment]
@JSv4 Noon Eastern tomorrow works for me. Feel free to send me the details.

**Comment by JSv4** [comment]
Awesome @arthur-clara, I'll add you to the invite.

**Comment by arthur-clara** [comment]
@pavitrabhalla 

https://www.ycombinator.com/assets/ycdc/Primer%20for%20post-money%20safe%20v1.1-2af8129e12effd9638eeab383b7309142c8f415e5cdb0bc210d573f779177a1c.pdf

The difference between the YC Original SAFE and the YC Post-Money SAFE are shown here.

The last two columns are the definitions of common SAFEs I have seen dealing with the startups that we deal with. 

The "Standard Post-Money SAFE" is the same definition as the "YC Post-Money SAFE" instance.
The "YC Original SAFE" is similar to the "Standard Pre-Money SAFE" I have seen EXCEPT that the YC Original definition includes the Pool top-up shares but most pre-money SAFEs I have seen do not.

**Comment by JSv4** [comment]
Just talking through this, and it probably makes sense to have "New Money" as a row here too, even if it's always excluded. 

Also, can we be a bit more descriptive with what "Standard" means? If these are variations on the original SAFE (a YC creation), maybe we call these YC Original __Plus__ X or YC Original __WITHOUT__ Y?

**Comment by JSv4** [comment]
Another wrinkle here:

"Other Safes, convertible notes and other similar convertibles" could get you into trouble. You can have multiple tranches of SAFEs and they may or may not affect some or all of the preceding tranches in a series.

**Comment by arthur-clara** [comment]
@JSv4 The definitions for other convertibles does tend to be "Converting securities" so it would only include tranches that convert at the equity financing, but that might be challenging to model.

Here are a couple of examples of text:

Example 1
Fully Diluted Capitalisation means (calculated as of immediately prior to the Equity Financing, without double-counting, and in each case calculated on an as converted to Ordinary Shares basis): 
(a)	all Shares issued and outstanding; and
(b)	all Converting Securities;
(c)	all issued and outstanding Options;
(d)	all Promised Options; and
(e)	the Unissued Pool, except that any increase to the Unissued Option Pool in connection with the Equity Financing shall only be included to the extent that the number of Promised Options exceeds the Unissued Option Pool prior to such increase.

Example 2
"Fully Diluted Share Capital" means the share capital of the Company calculated on a fully­ diluted basis, assuming conversion of all convertible securities and exercise of all outstanding options, warrants, phantom stock, stock appreciation rights, and other rights to acquire share capital of the Company, including all shares reserved and available for future grant under any equity incentive or similar plan of the Company, and/or any equity incentive or similar plan to be created or increased in connection with the Qualified Financing; provided, however, that except for the shares issued under this Agreement, the shares of the Company issued in a Qualified Financing and the shares of the Company issued upon conversion of any other current or future convertible debt or equity instruments in a Qualified Financing shall be excluded from this definition.

Example 3 (YC Post Money SAFE)
“Company Capitalization” is calculated as of immediately prior to the Equity Financing and (without double-counting, in each case calculated on an as-converted to Common Stock basis):
•	Includes all shares of Capital Stock issued and outstanding;
•	Includes all Converting Securities;
•	Includes all (i) issued and outstanding Options and (ii) Promised Options; and
•	Includes the Unissued Option Pool, except that any increase to the Unissued Option Pool in connection with the Equity Financing shall only be included to the extent that the number of Promised Options exceeds the Unissued Option Pool prior to such increase.

**Comment by JSv4** [comment]
@naveedn to add some thoughts from the Carta side.

**Comment by JSv4** [comment]
@dan-pulley to potentially outline the Pulley approach

**Comment by JSv4** [comment]
@jacobyavis, would be good to get some feedback from your team here too.

**Comment by pjohnmeyer** [comment]
**TWG notes**
Re: Promised options -- these aren't captured in the captable, but this is just a flag to inform the user that they need to consider them
Re: Optional pool increase -- there is some language that says it can be conditional on whether or not the increase is >= promised options, may need more options or language than just included/excluded

**Comment by jacobyavis** [comment]
The proposed model makes sense. In Shareworks we don't model complex convertibles ver well (mostly just simple CPNs), so we don't have any more suggestions to offer.

**Comment by LeeKevin** [comment]
The boolean model makes sense for us on the Carta side as well. 

Echoing @pjohnmeyer:

We will need to have separate booleans (or capture the conditional in some other way) for "Option pool increase" and "Option pool increase if 'Promised Options exceeds the Unissued Option Pool prior to such increase'"

**Comment by JSv4** [comment]
Suggested that "Other Safes, convertible notes and other similar convertibles" be "All other converting securities"

**Comment by JSv4** [comment]
Also agreed to split options as outlined by @LeeKevin

**Comment by arthur-clara** [comment]
@JSv4 

Working on a branch creating a proposal for integrating this issue but while looking at it, I noticed that the NoteConversionMechanism schema looks like it includes a valuation cap but it does not include conversionTiming or capitalizationDefinition fields. 

We can discuss but I would propose we add the robust capitalization definition object to the SAFEConversionMechanism, the NoteConversionMechanism and the PercentCapitalizationMechanism. We can leave the conversionTiming in the SAFEmechanism and the free text fields for capitalization definitions so that we don't create any breaking changes.

Additionally, I need a recommendation on what to name the type as the "CapitalizationDefinition" schema type already exists for conversion transactions.

**Comment by arthur-clara** [comment]
"include_outstanding_shares",
    "include_outstanding_options",
    "include_outstanding_unissued_options",
    "include_this_security",
    "include_other_converting_securities",
    "include_option_pool_topup_for_promised_options",
    "include_additional_option_pool_topup",
    "include_new_money"
    
    Current list of Boolean variables for discussion.
