### ISSUE TITLE
[Enhancement]: Explicitly support extraneous files

### ISSUE THREAD

**Issue by dan-pulley** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#360]
### Description of Enhancement :

The OCF zip should be able to contain other files, such as cert images, documents, etc. This issue and PR will introduce an explicit mechanism for this.

### Why is this Needed?

Being able to export and import a cap table losslessly means including all the vendor-specific enhancements and features.

**Comment by JSv4** [comment]
Definitely should revisit. We all see utility here, but adding further features atm is out of scope unless it's part of OCX or the validator.
