### ISSUE TITLE
[Enhancement]: Enhance Warrant Conversion Spec

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#362]
### Description of Enhancement :

A couple, inter-related limitations to be addressed here:

1. Our warrants *require* an exercise price at issuance, which is not always known. Make this optional
2. Our conversion mechanisms for warrants are pretty limited. Reflect some of the mechanisms we have for convertibles for warrants as well. 

### Why is this Needed?

This would allow for better coverage of real-world Warrant terms in our JSON schema. 

### Anything else we need to know?

Not at the moment.

**Comment by JSv4** [comment]
We had discussed copying some of the SAFE conversion mechanisms for warrant exercises. This is actually pretty significant. Also related to min/max issue and potential need for this in OCX.

**Comment by JSv4** [comment]
See also discussion in #372

**Comment by jacobyavis** [comment]
**Meeting Notes May 16**
* John has a PR up for this but is still waiting on some material from @arthur-clara before feeling totally confident
