### ISSUE TITLE
[Bug]: URL has dead link

### ISSUE THREAD

**Issue by naveedn** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#369]
### Current Behavior:

1. Navigate to link: https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/supplemental/VestingTerms/
2. Click the link, observe that it redirects to a 404 page

### Expected Behavior:

Expect link to navigate to: https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/explainers/VestingTerms/

**Comment by naveedn** [comment]
This bug can be closed by this PR.

**Comment by JSv4** [comment]
Closed by #385
