### ISSUE TITLE
[Question]: How to link a holder in stakeholder file to their underlying transaction history in the Transactions file 

### ISSUE THREAD

**Issue by TracyHappy123** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#376]

**Comment by JSv4** [comment]
Correct! You would want to look at issuance events that link to their stakeholder id. From those issuance events, get the `security_ids` they became owners of through the issuance transactions. Then you could traverse the transaction log to see what happened to those `security_ids` - e.g. are they still outstanding or were they transferred, repurchased, etc.
