### ISSUE TITLE
[Question]: How to model an RSA / RSA repurchase?

### ISSUE THREAD

**Issue by pjohnmeyer** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#379]
### Question:

It's unclear to me how a Restricted Stock Award issuance and/or repurchase is correctly modeled in OCF. Is there a way, or are we missing something from the schema?

1. The only reference to an RSA I can find in the schema documentation is in the documentation for the [StockParent](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/types/StockParent/) type. I cannot find any references to this type in the schema.

2. There is no mention of "types" of stock awards in [StockIssuance](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/issuance/StockIssuance/), so it is unclear how somebody could distinguish between a regular stock issuance and an RSA issuance.

3. I don't know if it would be appropriate to use a [PlanSecurityIssuance](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/issuance/PlanSecurityIssuance/) to describe an RSA issuance, but if it were, currently `compensation_type` only lists `OPTION` and `RSU`. Even if an RSA could be correctly modeled as a PlanSecurityIssuance, there is no corresponding PlanSecurityRepurchase.

**Comment by JSv4** [comment]
Need to review our notes, but a few initial thoughts:

- It probably should be a PlanSecurityIssuance type. 
   - Maybe we want to change the enumerations? To discuss.  
- We'd need a repurchase event in that case
- We may want to add some additional PlanSecurity types. @jacobyavis to provide some details on Stock Appreciation Rights.

**Comment by jacobyavis** [comment]
I'd propose collapsing `compensation_type` (`OPTION` and `RSU`) and `option_grant_type` (`NSO`, `ISO' and 'INTL') into a single field that describes the equity structure.

For name we might go with something generic like `plan_security_type`. For values I would want to make sure we include the following:

OPTION
OPTION_Q (qualified)
OPTION_NQ (non-qualified)
RSU (restricted share units)
RSA (restricted stock award)
CSAR(cash-settled stock appreciation rights)
SSAR(stock-settled stock appreciation rights)

cc @sachin-shrestha

**Comment by JSv4** [comment]
@jacobyavis, can you put together a quick PR for this and and see if there's a way to do this without creating a breaking change?

**Comment by JSv4** [comment]
@jacobyavis, just in case you're working on this, I was thinking about the plan-less options and mapping out some changes, and I think I have a way to cleanly fix RSAs, plan-less options and add your enumerations. Going to put something together to that effect.

**Comment by jacobyavis** [comment]
Thanks @JSv4, having a look now!

**Comment by pjohnmeyer** [comment]
#397 is not yet merged, reopening.

**Comment by jacobyavis** [comment]
Sorry Patrick, that's my bad. Good catch.
I think the reason I got confused is because PR #397 is also tagged to issue #393. Regardless, PR #396 is also yet to be merged as well
