### ISSUE TITLE
[Enhancement]: Add naveedn to repo so that he can be part of the "Committers" on github.

### ISSUE THREAD

**Issue by naveedn** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#387]
As title suggests, I'd like to get credit for working on OCF :)

**Comment by JSv4** [comment]
Hey @naveedn, before I change anything (and you totally should be a member of the repo), want to make sure we're looking at the same thing. I'm seeing you in the list of contributors. I also see you as having triage access as a member of the repo. Are you not seeing either of those? Or are you just not seeing your contributions reflect what you actually did? 

FYI, one thing I discovered matters here is whether you committed anything from a git client using an primary email that's not linked to and verified for your GitHub account. I was missing a bunch of contributions as well, but I found that adding and verifying my work email to my account solved the problem.
