### ISSUE TITLE
[Enhancement]: Support for plan-less option issuance

### ISSUE THREAD

**Issue by jacobyavis** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#393]
### Description of Enhancement :

OCF may need to support the ability to issue options without an associated plan.

### Why is this Needed?

This is something that (early stage?) companies do in real life but cannot be represented in OCF

### Anything else we need to know?

cc @JSv4 to fill the rest of this out

**Comment by JSv4** [comment]
Let's sidebar this. Have individual orgs discuss and report on whether they need / support this.
