### ISSUE TITLE
[Enhancement]: Compatibility with jsonschema2pojo

### ISSUE THREAD

**Issue by jacobyavis** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#413]
### Description of Enhancement :

To be able to create java classes for the OCF schema using popular library [jsonschema2pojo](https://www.jsonschema2pojo.org/)

### Why is this Needed?

Without the `javaType` property on the schemas, the library ends up creating duplicate classes. It does not know that two different references to Stakeholder are supposed to be the same object. 

Here's an example screenshot of how, even with proper $refs, jsonschema2pojo generates a local `Issuer.java` inside `schema/files` instead using schema/objects/Issuer.java

I also tried flattening the schema hierarchy before generating (not ideal), but I still got some duplicates files ending in __1, and also some duplicate enum classes created as inner classes...

### Anything else we need to know?

After reading some forums it seemed the easiest solution is to add `javaType` to the schemas. Tested and it works great so we just need to enforce it using a husky hook

[Reference in the docs](https://www.jsonschema2pojo.org/#:~:text=Extensions-,javaType,-jsonschema2pojo%20supports%20an)

**Comment by pjohnmeyer** [comment]
> Here's an example screenshot

@jacobyavis I don't see the screenshot?

**Comment by regebro** [comment]
Wouldn't the reasonable way to use this schema from Java be to use a common library? It seems strange to me that everyone using this schema would generate their own classes, but maybe that's because I'm from the Python world.

**Comment by jacobyavis** [comment]
Code generation is pretty common in Java projects. At least in my opinion, it's much quicker to run a code-gen lib like `jsonschema2pojo` than to work on maintaining a library in parity with the schema.
