### ISSUE TITLE
[Enhancement]: Accommodating jurisdictions that maintain authorized share count at company level instead of at class level

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#415]
### Description of Enhancement :

1. Add an optional variable at the issuer level for share capital or total number of share class.
2. Make the number of authorized shares at the share class level optional. 

### Why is this Needed?

Several common jurisdictions for startup holding companies such as Cayman Islands and Abu Dhabi Global Market do not require that authorized share capital and number of authorized shares to be connected to specific share classes. Instead this is a company level variable. Right now, OCTF v1 requires number of authorized shares to be added per share class. This does not make sense for these jurisdictions.

### Anything else we need to know

This issue has the knock on effect of asking how we would deal with amending number of authorized shares because in these jurisdictions, it is done at the company / issuer level instead of the share class level.

**Comment by JSv4** [comment]
@arthur-clara, so, in these jurisdictions, you can have multiple classes authorized, and you can issue any number of shares of stock of those classes, so long as the total issued is less than the total shares authorized for all classes?

**Comment by arthur-clara** [comment]
@JSv4  That is correct.

When I set up the company, there is a shareholders' resolution that has language similar to:

The Company be incorporated in Abu Dhabi Global Market with an authorised share capital of USD 1,000 comprising 10,000,000 shares of par value USD 0.0001 each.

The Articles can set up as many share classes (with par values of USD 0.0001) as desired and issue shares across them as desired as long as the sum of issued shares for all classes does not exceed 10,000,000 in this example. 

If it does, the TOTAL authorised share capital needs to be amended and then those additional authorised shares can be issued to any class.

**Comment by JSv4** [comment]
We could include this, but we'll need to keep this required at the StockClass level. We could probably create some kind of jsonschema validation to support a number or an enum and then create an issuer-level optional field for total authorized.
