### ISSUE TITLE
[Enhancement]: v1.1 Release

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#422]
### Description of Enhancement :

Do the actual 1.1 release

### Why is this Needed?

Let's get some reps on the release process and we've made significant changes since 1.0

**Comment by pjohnmeyer** [comment]
I've created the tag locally and uploaded to https://schema.opencaptablecoalition.com/v/1.1.0/files/OCFManifestFile.schema.json

**Comment by pjohnmeyer** [comment]
**Release:** https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/releases/tag/v1.1.0
**Issues found:**
- #429 
- #430
