### ISSUE TITLE
HOW does OCF support one stakeholder has more than one relationship with a issuer 

### ISSUE THREAD

**Issue by TracyHappy123** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#424]
Need your help to answer the question below: How does OCF support this use case, which is one stakeholder has more than one relationship with an issuer. For example, If a stakeholder is an ex-employee of an issuer  and now is a consultant of the same issuer .

One possible solution could be we create two stakehold files for one stakehold with the same ID and stakeholder name but with the different value for current_relationship filed, which means, one file is ex-employee, the second file is a consultant. Is this the right solution or any suggestion.

**Comment by JSv4** [comment]
Hey @TracyHappy123, thanks for the question! We actually have a pending issue to resolve this.  See issue #373 for the latest discussion. We haven't quite decided how to change the schema to support this. My personal preference is to add an event type for stakeholders to add or remove relationships and then you'd be able to traverse the events stack to get the list of current and/or expired relationships for each stakeholder. Another option is to make the field a list on the stakeholder object with either a date range of when the relationship was valid or a boolean to flag active or inactive relationships. Thoughts on the preferred resolution here? We'd certainly welcome a contribution if you're open to tackling a PR.

**Comment by JSv4** [comment]
I'm going to close this, but please feel free to continue the conversation in #373
