### ISSUE TITLE
[Enhancement]: Make documentation consistent with the StockIssuance schema

### ISSUE THREAD

**Issue by RahulS-97** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#437]
### Description of Enhancement :
The number of required fields for **StockIssuance** on the OCF [documentation](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/issuance/StockIssuance/) are 9 but in the [Schema](https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/objects/transactions/issuance/StockIssuance.schema.json) file for StockIssuance there are only 4 required fields.

### Why is this Needed?

This will sync StockIssuance schema on OCF Docs with Github

### Anything else we need to know?

- https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/objects/transactions/issuance/StockIssuance.schema.json
- https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/issuance/StockIssuance/

**Comment by JSv4** [comment]
@JSv4 to respond. If we have documentation on this composition quirk, to note that here, and, if not, will open an issue to improve docs.

**Comment by JSv4** [comment]
This is due to our documentation always being synced from the main branch. We are going to lock them to the latest release and then, eventually, have versioned documents.
