### ISSUE TITLE
[Enhancement]: Tag Specific Issuances with "Financing" Object

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#445]
### Description of Enhancement :

In OCX and other lawyer-facing formats, being able to see all of the issuances created as part of a "financing" - however that is defined - is very useful. Adding a financing object and allowing issuances to refer to the financing id would facilitate this.

### Why is this Needed?

Support of human workflows.

### Anything else we need to know?

Question is whether any platform actually captures this information?

**Comment by JSv4** [comment]
TWG

- Seems pretty easy to add (Transaction Object plus a ref field in the issuance primitive).
- Another example of where this is likely (besides Notes and SAFEs) would be YC issuance of Common, typically in a Series A

**Comment by JSv4** [comment]
@lavens to be assigned

**Comment by lavens** [comment]
`Seems pretty easy to add (Transaction Object plus a ref field in the issuance primitive).`
@JSv4 Just want to confirm, were you envisioning that a `Financing` would be represented as a transaction eg. `TX_FINANCING`.

I put up a PR with this approach. https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/468
Happy to update if you have other thoughts.
