### ISSUE TITLE
[Enhancement]: Split Schema Validation Tools Into Separate Repo

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#447]
### Description of Enhancement :

To improve the modularity of the code and facilitate the xState state validation work, split our schema validation tools into a separate repo.

### Why is this Needed?

See above.

### Anything else we need to know?

Nope

**Comment by JSv4** [comment]
@arthur-clara, is this helpful? If not, I may just close this to trim our open issues.

**Comment by arthur-clara** [comment]
@JSv4 Not a priority for now
