### ISSUE TITLE
[QUESTION] - could you pls. explain the details of " StockAcceptance": persona, use case and differences with approval

### ISSUE THREAD

**Issue by TracyHappy123** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#448]
### Question:

For StockAccptance Object introduced on https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/acceptance/StockAcceptance/, could you pls. share the details of use case, especially who should accept the stock transaction? And differences between approval?

**Comment by JSv4** [comment]
Going to add an issue to improve lifecycle event documentation with flowcharts
