### ISSUE TITLE
[Enhancement]: Add TIN Format Enum

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#451]
### Description of Enhancement :

Enumerate some common TIN

### Why is this Needed?

Current Tax ID is unstructured string. At least trying to capture what format it represents would improve compatibility.

**Comment by JSv4** [comment]
**TWG Notes**

1. Create an enum
2. Add an optional unstructured description field required if enum is OTHER

**Comment by JSv4** [comment]
We want to see if we can add this without making a breaking change. Should be doable. If not, let's put it in the notes. for v2

**Comment by Sumukh** [comment]
I played around with a structured format for US Tax IDs, but all it would do is validate against a regex.

**Comment by pjohnmeyer** [comment]
Closed per TWG meeting: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/475#issuecomment-2020882134
