### ISSUE TITLE
Evaluate Need for One-to-Many Association between Stock class and Stock plan?

### ISSUE THREAD

**Issue by dahal** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#461]
First of all, a great initiative. We are currently building OpenSource captable management platform [OpenCap](https://github.com/opencapco/opencap.co) and we will follow the [Open Cap Table Coalition](https://www.opencaptablecoalition.com/format) format as much as possible and would love to collaborate.

I wanted to clarify what the expected associations are between these two tables/schemas, one to one or one to many? cc @JSv4

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/fec5c3962e15735caf0607b48d3ae2484efea59e/samples/StockPlans.ocf.json#L11

We are going with one to many association, that seems to make more sense.
https://github.com/opencapco/opencap.co/pull/93/files#diff-5b443964f4f3a611682db8f7e02177b0a8c632b2039e2bd5e4dd7347815c565cR165-R217

**Comment by JSv4** [comment]
Hey @dahal, thanks for the question. Each stock plan can only have one stock class linked to it, but you can have multiple plans linked to the same stock class - e.g. you could have three different stock plans all issuing common stock, which would all have the same stock class id. That in line with what you guys are expecting?

**Comment by jarrettq** [comment]
👋 additional context - Canadian corporations do have the ability to designate multiple share "classes" within a given stock/equity plan, which current versions of the OCF spec don't support. (e.g. An option pool of 5,000,000 shares, which can be issued in the form of option grants for either Voting or Non-Voting Common shares).

The Mantle team is going to look to provide some recommendations on how this scenario could be captured with adjustments to the OCF spec.

To make sure we're being as specific as we can be with the wording involved here - with Canadian capitalization definitions, the typical language we could see would indicate:
> (i) an unlimited number of Common Shares, **_issuable in series_**, of which an unlimited number are designated as Voting Common Shares (the “Voting Common Shares”) and an unlimited number are designated as Non-Voting Common Shares (the “Non-Voting Common Shares” and together with the Voting Common Shares, the “Common Shares”) 

So there's an implied hierarchical relationship between the overarching Common Share **class** and the Voting Common & Non-Voting Common **series** within it.

This also winds up being expressed in the Definitions section of Equity Incentive Plans:
> "Common Shares" means the Voting Common Shares or the Non-Voting Common Shares in the capital of the Company;

At which point the individual option grants will specify which series the options would exercise into.

**Comment by JSv4** [comment]
@jarrettq, just had an interesting discussion about this on the Law Firm Working Group. It _can theoretically_ happen in the U.S. (which we knew), but it _does_ happen now and again as well. Since it is something that happens in U.S. companies, though rarely, it'd be great to see what this might look like in OCF. If it's a light lift, definitely worth including.

**Comment by jarrettq** [comment]
@JSv4 ooo, great news 🙌 . The introduction of `equity_compensation_issuance` transactions has already opened the door, as well - the inclusion of non-plan awards added `stock_class_id` as a field to the issuance transaction, so it may primarily just be a matter of swapping in a `stock_class_ids` list for the `stock_class_id` field in the Stock Plan object and then adjusting validation logic and documentation as appropriate.

**Comment by JSv4** [comment]
Another situation this will be more common is when companies are going public or have gone public. Some of the folks on the call noted they have seen this recently as well.
