### ISSUE TITLE
[Enhancement]: Add Structural Validation for Required Field & Object Types Enum

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#470]
### Description of Enhancement :

As flagged in #457, we had a transaction schema committed for Issuer Authorized Share Adjustment that had the wrong required field name AND an object_type that was not in the object type enum. Either the test failed to trip the GitHub action or our test doesn't cover either situation. I know it doesn't cover checks that fields marked as required actually exist, but I am surprised the missing ObjectType didn't cause a validation error somewhere. 

I propose adding a validation test for BOTH in the validate schema tooling.  

### Why is this Needed?

We didn't catch a schema with two issues making it to a release. 

### Anything else we need to know?

Nope

**Comment by JSv4** [comment]
- This may be as simple as just making sure there is a sample. Can check for that. 
- **ALSO** add additional documentation to walk someone through adding a schema and what is required - e.g. a sample.

**Comment by jacobyavis** [comment]
Solution for this is two-phase

1. Ensure when we're validating schemas that any `object_type`'s `const` value also appears in the enum list on `ObjectType.schema.json`
2. Ensure that for every object type, at least one sample exists in the samples directory
