### ISSUE TITLE
[Enhancement]: Add support for 'balance cancellation' when doing a Transfer

### ISSUE THREAD

**Issue by jacobyavis** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#483]
### Description of Enhancement :

The schema for Stock Transfer does not support a situation where there's a partial transfer with the _balance cancelled_. Currently the only way to do this would be to issue a balance certificate then subsequently cancel it. The problem with this is platforms that support this will not have a `security_id` to reference for the temp balance certificate.

### Why is this Needed?

To properly represent a partial transfer+ balance cancellation transaction (such as is possible in Shareworks), since TX_STOCK_TRANSFER expects all shares to go to new security_ids (either transferee certificates or a balance certificate)

**Comment by pjohnmeyer** [comment]
TWG: At issue here is the fact that transfers are considered "terminal" transactions in OCF.

From https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/blob/86b1229088c8a69ba58547c07dfb06401bb2e2db/docs/explainers/TraversingTransactions.md:

> 6. **Transfer** - transactions composed of [Transfer](../schema_markdown/schema/primitives/objects/transactions/transfer/Transfer.md) - which includes `StockTransfer`, `WarrantTransfer`, `PlanSecurityTransfer` and `ConvertibleTransfer` - transactions must link to the `security_id` of the original issuance the transferred securities were issued as a part of. This transfer can be in whole or in part, and it can be to a single new issuance or to multiple new issuances. If the transfer is in-part, any remaining securities must be issued with a new `security_id` which should be referred to as the `balance_security_id`. The `security_id`s of the resulting issuances to the transferees should be recorded in an array in the `resulting_security_ids` field.

In the case as @jacobyavis describes, if we follow this documentation, the solution requires creating an issuance that was never actually issued, and then cancel / retract it. That seems misleading.

The approach in #486 would resolve this issue. We could also choose to say that partial transfers are _not_ terminal transactions, which would allow the sequence to be ISSUANCE, TRANSFER, CANCEL on the initial security.

@pjohnmeyer to refer this issue to the law firm working group to determine two things:

1. Does this really happen, or is this, as Jake put it, a "Shareworks-ism"?
2. If it does, how is it mechanized in reality?

**Comment by pjohnmeyer** [comment]
This is on the agenda for LFWG Monday 6 May.

**Comment by pjohnmeyer** [comment]
This remains an open question as it was not discussed at yesterday's call.

**Comment by jacobyavis** [comment]
This idea has been largely shut down -- not a standard practice by any means
