### ISSUE TITLE
[Enhancement]: Add Encumbrance Details to Securities

### ISSUE THREAD

**Issue by mrosendin** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#493]
### Description of Enhancement :

I propose adding a feature to the Open Cap Table Format to include details about whether a security is encumbered. This enhancement should allow users to clearly identify if any security is currently used as collateral or is otherwise encumbered, and provide specific details regarding the nature of such encumbrances.

### Why is this Needed?

In financial dealings, it's crucial to understand the status of securities, particularly if they are encumbered—for example, when used as collateral for a loan. Knowing whether a security is encumbered, and the specifics of the encumbrance (e.g., lien holder, terms of the encumbrance), is essential for risk assessment, legal compliance, and accurate valuation of assets. Currently, the Open Cap Table Format does not provide a way to track this information, which can lead to oversight and mismanagement of securities.

### Anything else we need to know?

Implementing this feature should include:

- An indicator of whether a security is encumbered or unencumbered.
- Detailed fields describing the type of encumbrance, the party holding the claim or lien, and specific terms or conditions associated with the encumbrance.
- Definitions and possible transaction schemas for encumbering and unencumbering assets, as well as for the sale of encumbered assets.
- This enhancement would align the Open Cap Table Format with common financial practices and increase its utility for managing more complex capitalization tables.

I can provide a PR for this, but it may take a few months.

**Comment by JSv4** [comment]
Thanks for the suggestion @mrosendin. I think this is a bit beyond the scope of what we're trying to track in the core standard. One thing we'd talked about in the past was having a slightly more modular architecture that would support mixin schemas for certain additional features - e.g., maybe there'd be an "encumbrance" file that could sit in the ocf archive and provide relevant information for applicable shares. All that to say, we'd welcome further discussion on this, but it probably doesn't belong in the OCF standard itself.
